/** @format */

export const CANDIDATE_LIST_REQUEST = 'CANDIDATE_LIST_REQUEST'
export const CANDIDATE_LIST_SUCCESS = 'CANDIDATE_LIST_SUCCESS'
export const CANDIDATE_LIST_FAIL = 'CANDIDATE_LIST_REQUEST'

export const CANDIDATE_PROFILE_REQUEST = 'CANDIDATE_PROFILE_REQUEST'
export const CANDIDATE_PROFILE_SUCCESS = 'CANDIDATE_PROFILE_SUCCESS'
export const CANDIDATE_PROFILE_FAIL = 'CANDIDATE_PROFILE_REQUEST'

export const CANDIDATE_STATUS_REQUEST = 'CANDIDATE_STATUS_REQUEST'
export const CANDIDATE_STATUS_SUCCESS = 'CANDIDATE_STATUS_SUCCESS'
export const CANDIDATE_STATUS_FAIL = 'CANDIDATE_STATUS_REQUEST'

export const CANDIDATE_STATUS_LIST_REQUEST = 'CANDIDATE_STATUS_LIST_REQUEST'
export const CANDIDATE_STATUS_LIST_SUCCESS = 'CANDIDATE_STATUS_LIST_SUCCESS'
export const CANDIDATE_STATUS_LIST_FAIL = 'CANDIDATE_STATUS_LIST_REQUEST'
